My homework
ZhdanAnna/zhdan pull request #4
Opened 2022-08-16 18:30 UTC by ZhdanAnna

2022-08-16 18:31 UTC, ZhdanAnna commented
@NadiaBovshis Review please

2022-08-16 19:15 UTC, NadiaBovshis requested changes

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +//+1 Напишите переменные и константы всех базовых типов данных: int, UInt, float, double, string. У чисел вывести их минимальные и максимальные значения. //
1. Константы и переменные не проинициализированы исходя из их типов.
2. Достаточно выведения максимальных и минимальных значений типов указанных в задании, этот пункт можно не исправлять

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +//2) Создайте список товаров с различными характеристиками (количество, название). Используйте typealias.
Задание выполнено без использования typealias

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +let pi: Double = 3.1415926
У типа double есть проперти pi

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +let radians: Double = (2 * pi) / 360
Не корректное вычисление перевода угла в градусах в радианы

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +print("\n \(name) \t \(sername) \t \(age) \t \(address) \t \(hobby) \t \(name) \t \(sername) \t \(age) \t \(address) \t \(hobby)")
Пробелы до после \n и \t излишни, т.к. они добавляют пробелы и в введенный текст

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +let resultTask5: String = "\(name)\t" + String(age1)
В данном случае не принципиально использование просто пробела " " или \t, но надо помнить, что \t это табуляция (длинный пробел)

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +let fullName: String = "\(firstName)" + " " + "\(lastName)"
Избыточно использование конструкции `"\()"`, т.к. константы и так являются строками

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +print("\(infoAboutAnna.0), \(infoAboutAnna.1), \(infoAboutAnna.2), \(infoAboutAnna.3), \(infoAboutAnna.4)")
Избыточно, т.к. выше выводится тем же способом

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +print(bedoqureOne.self.2)
Третий способ фактически дублирует первый, нужен другой вариант, используй то что у тебя именованные параметры кортежа.
Так же требуется вывести каждый параметр тремя способами.

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +var temprature: Double = 23
Неправильно создан кортеж, читай задание)))))

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +print("Day is \(changedTuple.0), _, _, averageTemperature is \(changedTuple.3)")
Читай внимательно задание, требуется прочитать кортеж с учётом только двух параметров, остальные не учитавать. Мы тобой обсуждали картежи в которых нас интересуют только определённые параметры

2022-08-16 19:15 UTC, NadiaBovshis commented on Contents.swift
> +*/
Задание не выполнено. Не используется кортеж как переменная

2022-08-21 08:22 UTC, NadiaBovshis requested changes

2022-08-21 08:22 UTC, NadiaBovshis commented on HW1.playground/Contents.swift
> +print ("\(operand1) + \(operand2) = \(addition)")
Форматирование - лишний пробел строки 69-71

2022-08-21 08:22 UTC, NadiaBovshis commented on HW1.playground/Contents.swift
> +let fullName: String = "\(firstName)" + " " + "\(lastName)"
Избыточно использование конструкции `"\()"`, т.к. константы и так являются строками

2022-08-21 08:32 UTC, NadiaBovshis approved these changes

2022-08-21 08:32 UTC, merged